### ISSUE TITLE
Unable to use Bed... 

### ISSUE THREAD

**Issue by ebeneezersquid** [ssblur/Just-What-I-Needed-Mod#1]
Not sure why, may be a mod interaction bug, but with JWIN installed on 1.8 I was unable to sleep in a bed on my single player game. 

during the day, activating the bed gave me the standard "need to wait for night" message, at night, clicking on the bed nothing happened.

**Comment by ssblur** [comment]
Sorry about the delay. Closed on curseforge after patch published, has not been reopened, closing here because presumed fixed.
