### ISSUE TITLE
(1.8.9) (JWIN_v0.11.1_1.8.9) Wolves & Horse Issues

### ISSUE THREAD

**Issue by DarcClan** [ssblur/Just-What-I-Needed-Mod#3]
Wolves sometimes (hard to reproduce) stop following/ act like you haven't tamed them, except won't fight back if hit, applys to baby wolves bred from broken wolves. Horses also refuse to be broken in, you mount the horse, but it doesn't kick you off or ever become tamed, it just wanders with you on its back.

**Comment by ssblur** [comment]
This is an issue with the Animal 'Sit' command added by JWIN, which is a feature I intend to remove due to its broken implementation.
For the moment, I suggest you disable this feature in the configuration file.
Terribly sorry about this, the issue will be resolved in the next iteration of the mod.

**Comment by ssblur** [comment]
Forgot to thank you for posting this issue earlier, but thank you! I always appreciate such input!
