### ISSUE TITLE
Thaumcraft 5 + Ore Conversion = Game Breaking Crash

### ISSUE THREAD

**Issue by Croebh** [ssblur/Just-What-I-Needed-Mod#5]
While running a modpack including Thaumcraft 5, having the Ore Conversion option enabled causes a feedback loop of items spawning and console errors when a player drops, and then attempts to pick up, one of the plantable vis crystals.

Once this option is disabled, the extra items stop spawning, and the errors stop. I have not noted any other items that this affects. 

Error Affects both SSP and SMP

Versions Involved:
Thaumcraft - Thaumcraft-1.8.9-5.2.1
JWIN - JWIN_v0.12.0_1.8.9

Server-Crashlog
http://pastebin.com/VzrBZgAz

Server-Log
http://pastebin.com/TYu0WE4u

Note the repeating error at the end of the server log. I actually had to remove several thousand lines of that same error in order to post the log to pastebin.

**Comment by ssblur** [comment]
I have not been able to replicate this issue, could you provide me any additional information?

**Comment by ssblur** [comment]
Due to lack of additional information and replicability, this ticket is being closed. If you can provide any additional information to aid in replication, feel free to open a new ticket.
