### ISSUE TITLE
Incompatible with Resourceful Crops

### ISSUE THREAD

**Issue by zulucap** [ssblur/Just-What-I-Needed-Mod#6]
There appears to be a compatibility issue with Resourceful Crops' right click harvesting. Resourceful Crops has their own right-click harvesting for their crops. When right-click harvesting is enabled in JWIN Mod, plants cannot be harvested from RC at all (even breaking the crop does not work.) I have been successful in harvesting when I disable right-click harvesting in JWIN, but then all other crops lose the right-click harvest ability. I suspect this has to do with how RC handles their drops. A possible solution may be to default to vanilla harvesting for RC crops and allow that mod to take over the harvesting function, while still allowing JWIN to handle right-click harvesting (if enabled) for all other crops.

**Comment by ssblur** [comment]
This will be resolved in version 0.13.0, thank you for reporting.
