### ISSUE TITLE
Red cross symbol on all mobs (1.9)

### ISSUE THREAD

**Issue by heanz** [ssblur/Just-What-I-Needed-Mod#8]
Issue Picture:
http://pasteboard.co/2DatqOaU.png

Forge 1811
Additional Addons:
http://pasteboard.co/2DawvEcp.png

**Comment by ssblur** [comment]
Alright, I found the problem, it was with a changed field name in 1.9 from 1.8.x. Thank you for reporting, will be fixed in next version.

**Comment by heanz** [comment]
Great support man.

**Comment by axzxc1236** [comment]
Somehow I have the same issue now.
