### ISSUE TITLE
JWIN Right click feature not working

### ISSUE THREAD

**Issue by MwM-Bliss** [ssblur/Just-What-I-Needed-Mod#9]
I installed JWIN mod for minecraft1.9 and have a problem using the right click harvest feature. I have it enabled in configs but it still does not work in game. Please help.

**Comment by ssblur** [comment]
Alright, I am working on it, it will be fixed in the next release. I will close this issue once the problem is identified.

**Comment by ssblur** [comment]
Sorry about the massive delay, school has been rather pressing. Problem has been identified, was a change in the way Forge handles interact hooks.
